#version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: django-backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - db
    #command: >
    #  sh -c "
    #  python manage.py migrate &&
    #  python manage.py runserver 0.0.0.0:8000"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: react-frontend
    ports:
      - "3000:80"
    volumes:
      - frontend_data:/frontend
     # - frontend_modules_data:/frontend/node_modules  # Evita conflictos entre el host y el contenedor
    env_file:
      - frontend/.env
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: proyecto_final
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  frontend_data:
  #frontend_modules_data:
